"use client";
import "./globals.css";
import Navbar from "../components/navbar/Navbar";
import { Inter } from "next/font/google";
import Sidebar from "@/components/sidebar/Sidebar";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [isOpen, setIsOpen] = useState(false);

  const handleToggle = () => setIsOpen((prev) => !prev);

  return (
    <html lang="en">
      <body>
        <div>
          <Navbar handleToggle={handleToggle} />
          <div className="lg:flex">
            <div className="lg:w-[16rem]">
              <Sidebar isOpen={isOpen} />
            </div>
            <div className="lg:flex-1">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
